name: Batch Analyzer Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  batch-analyzer-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run unittest
        run: python3 -m unittest discover -v file_analyzer_batch/tests
